DROP TRIGGER IF EXISTS update_users_updated_at ON users;
ALTER TABLE users DROP COLUMN IF EXISTS updated_at;

ALTER TABLE users ADD COLUMN updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL;

CREATE TRIGGER update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
